version: "1"
services:
  iac-dev-container:
    container_name: DevContainer
    build:
      context: .
      dockerfile: Dockerfile
    #    image: ghcr.io/maxotta/iac-development-container:latest
    volumes:
      - "iac-dev-container-data:/var/iac-dev-container-data" # there can be issue
      - "../..:/workspace"
volumes:
  iac-dev-container-data:
    external: false
