- name: Update apt cache
  apt:
    update_cache: yes

- name: Install apt-utils
  apt:
    name: apt-utils
    state: present
  become: yes

- name: Install Apache (or other backend app)
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Ensure Apache is running
  service:
    name: apache2
    state: started

#- name: Run NGINX in Docker
#  docker_container:
#    name: backend-nginx
#    image: nginx:latest
#    state: started
#    restart_policy: unless-stopped
#    pull: yes
#    ports:
#      - "80:80"
#    volumes:
#      - /tmp/index.html:/usr/share/nginx/html/index.html