- name: Create a simple index.html file
  copy:
    dest: /tmp/index.html
    content: |
      <html>
      <head><title>Backend</title></head>
      <body>
      <h1>This is Backend Server {{ ansible_host }}</h1>
      </body>
      </html>

- name: Run NGINX in Docker
  docker_container:
    name: backend-nginx
    image: nginx:latest
    state: started
    restart_policy: unless-stopped
    pull: yes
    ports:
      - "80:80"
    volumes:
      - /tmp/index.html:/usr/share/nginx/html/index.html
