- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Apache
  apt:
    name: apache2
    state: present
  become: yes

- name: Ensure Apache service is running
  systemd:
    name: apache2
    state: started
    enabled: yes
  become: yes

- name: Create a simple index.html file
  copy:
    dest: /var/www/html/index.html
    content: |
      <html>
      <head><title>Backend</title></head>
      <body>
      <h1>This is Backend Server {{ ansible_host }}</h1>
      </body>
      </html>
