- name: Create a directory for Apache HTML files
  file:
    path: /tmp/apache_html
    state: directory

- name: Deploy dynamic index.html using template
  template:
    src:  "/home/runner/work/iac-loadbalancer-automation/iac-loadbalancer-automation/ansible/roles/backend/templates/index.html.j2"
    dest: /tmp/apache_html/index.html
  become: yes

- name: Run Apache container on backend
  docker_container:
    name: apache_backend
    image: httpd:latest
    state: started
    restart_policy: unless-stopped
    pull: yes
    ports:
      - "80:80"
    volumes:
      - /tmp/apache_html:/usr/local/apache2/htdocs/