- name: Update apt cache
  apt:
    update_cache: yes

- name: Install python3-venv if not installed
  apt:
    name: python3-venv
    state: present
  become: yes

- name: Create a Python virtual environment
  command: python3 -m venv /opt/venv
  become: yes

- name: Install Python Docker module in the virtual environment
  pip:
    name: docker
    virtualenv: /opt/venv
  become: yes
