- name: Configure Backends
  hosts: backend
  become: true
  vars:
    ansible_python_interpreter: /opt/hostedtoolcache/Python/3.9.20/x64/bin/python3  # Ujistěte se, že máte správnou cestu k Pythonu
  roles:
    - backend

- name: Configure Load Balancer
  hosts: load-balancer
  become: true
  vars:
    ansible_python_interpreter: /opt/hostedtoolcache/Python/3.9.20/x64/bin/python3  # Ujistěte se, že máte správnou cestu k Pythonu
  roles:
    - load_balancer

- name: Install Docker SDK for Python
  hosts: all  # To se provede na všech hostech
  become: true
  vars:
    ansible_python_interpreter: /opt/hostedtoolcache/Python/3.9.20/x64/bin/python3  # Ujistěte se, že používáte správný Python
  tasks:
    - name: Install docker SDK for Python
      pip:
        name: docker==4.4.4
        executable: /opt/hostedtoolcache/Python/3.9.20/x64/bin/pip  # Ujistěte se, že pip odpovídá Pythonu