- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker.io
    state: present
  become: yes

- name: Ensure Docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Check Python version
  command: python3 --version
  register: python_version
  changed_when: false
  failed_when: false

- name: Debug Python version
  debug:
    var: python_version.stdout

- name: Check Docker version
  command: docker --version
  register: docker_version
  changed_when: false
  failed_when: false

- name: Debug Docker version
  debug:
    var: docker_version.stdout

- name: Create a directory for NGINX config
  file:
    path: /tmp/nginx
    state: directory

- name: Generate NGINX configuration
  template:
    src: nginx.conf.j2
    dest: /tmp/nginx/nginx.conf

- name: Install NGINX webserver in Docker container as Load Balancer
  docker_container:
    name: webserver
    image: nginx:latest
    state: started
    restart_policy: unless-stopped
    pull: yes
    ports:
    - "80:80"
    volumes:
    - /tmp/nginx/nginx.conf:/etc/nginx/nginx.conf

- name: Debug backend IPs
  debug:
    var: backend_ips

