- name: Update apt cache
  apt:
    update_cache: yes

- name: Install python3-venv if not installed
  apt:
    name: python3-venv
    state: present
  become: yes

- name: Create a Python virtual environment
  command: python3 -m venv /opt/venv
  become: yes

- name: Install Python Docker module in the virtual environment
  pip:
    name: docker
    virtualenv: /opt/venv
  become: yes

- name: Install Docker
  apt:
    name: docker.io
    state: present
  become: yes

- name: Ensure Docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Create a directory for Apache config
  file:
    path: /tmp/apache
    state: directory

- name: Generate Apache Load Balancer configuration
  template:
    src: apache
    dest: /tmp/apache/apache.conf

- name: Install Apache webserver in Docker container as Load Balancer
  docker_container:
    name: apache_load_balancer
    image: httpd:latest
    state: started
    restart_policy: unless-stopped
    pull: yes
    ports:
      - "80:80"
    volumes:
      - /tmp/apache/apache.conf:/usr/local/apache2/conf/httpd.conf

- name: Install Apache
  apt:
    name: apache2
    state: present
  become: yes

- name: Enable required Apache modules
  command: a2enmod proxy proxy_http proxy_balancer lbmethod_byrequests
  become: yes

- name: Ensure Apache service is restarted after enabling modules
  systemd:
    name: apache2
    state: restarted
  become: yes

- name: Move generated Apache configuration to the correct directory
  copy:
    src: /tmp/apache/apache.conf
    dest: /etc/apache2/sites-available/apache.conf
    owner: root
    group: root
    mode: '0644'
    remote_src: yes
  become: yes

- name: Disable the default Apache site
  command: a2dissite 000-default.conf
  become: yes
  ignore_errors: yes  # Pro případ, že je již deaktivováno.

- name: Enable the custom Apache configuration
  command: a2ensite apache.conf
  become: yes

- name: Ensure Apache service is restarted after configuration changes
  systemd:
    name: apache2
    state: restarted
  become: yes