- name: Create a directory for NGINX config
  file:
    path: /tmp/nginx
    state: directory

- name: Generate NGINX configuration
  template:
    src: nginx.conf.j2
    dest: /tmp/nginx/nginx.conf

- name: Install NGINX webserver in Docker container as Load Balancer
  docker_container:
    name: webserver
    image: nginx:latest
    state: started
    restart_policy: unless-stopped
    pull: yes
    ports:
    - "80:80"
    volumes:
    - /tmp/nginx/nginx.conf:/etc/nginx/nginx.conf
