- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install apt-utils
  apt:
    name: apt-utils
    state: present
    update_cache: yes

- name: Install Nginx Web Server in Docker container
  docker_container:
    name: webserver
    image: nginx:latest
    state: started
    restart_policy: unless-stopped
    pull: yes
    ports:
    - "80:80"

- name: Copy NGINX configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644

- name: Validate NGINX configuration
  command: nginx -t
  register: nginx_test
  ignore_errors: yes

- name: Fail if NGINX configuration is invalid
  fail:
    msg: "NGINX configuration is invalid"
  when: nginx_test.rc != 0

- name: Ensure NGINX is enabled and started
  service:
    name: nginx
    state: started
    enabled: yes