- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker.io
    state: present
  become: yes

- name: Ensure Docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Create a directory for Apache config
  file:
    path: /tmp/apache
    state: directory

- name: Generate Apache Load Balancer configuration
  template:
    src: apache
    dest: /tmp/apache/apache.conf

- name: Install Apache webserver in Docker container as Load Balancer
  docker_container:
    name: apache_load_balancer
    image: httpd:latest
    state: started
    restart_policy: unless-stopped
    pull: yes
    ports:
      - "80:80"
    volumes:
      - /tmp/apache/apache.conf:/usr/local/apache2/conf/httpd.conf

- name: Debug backend IPs
  debug:
    var: backend_ips
