name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.6

      - name: Terraform Init and Apply
        run: |
          terraform init
          terraform apply -auto-approve
          terraform output -json > inventory.json

      - name: Generate Ansible Inventory
        run: python3 generate_inventory.py

      - name: Setup Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.yml ansible/playbook.yml
