name: Deploy Project

on:
  release:
    types: [published]

jobs:
  push_to_registries:
    name: Push Docker image to the ghcr.io registry
    runs-on: ubuntu-20.04
    permissions:
        contents: read
        packages: write
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6  # Replace with your required version

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 4: Install Ansible
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible 

      - name: Write SSH Private Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > id_ecdsa
          chmod 600 id_ecdsa
          cat id_ecdsa

      - name: Write SSH Public Key
        env:
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        run: |
          echo "$SSH_PUBLIC_KEY" > id_ecdsa.pub
          chmod 600 id_ecdsa.pub        

      - name: Fix provider permissions
        run: chmod +x .terraform/providers/registry.terraform.io/opennebula/opennebula/1.4.1/linux_amd64/terraform-provider-opennebula_v1.4.1

      # Step 5: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Step 6: Plan Terraform deployment
      - name: Plan Terraform
        run: terraform plan

      # Step 7: Apply Terraform configuration
      - name: Apply Terraform
        run: terraform apply -auto-approve

      # Step 10: Generate backend_ips.json
      - name: Generate backend_ips.json and load_balancer_ip.json
        run: |
          terraform output -json backend_ips > backend_ips.json
          terraform output -json load_balancer_ip > load_balancer_ip.json

      # Step 11: Wait for files to be written
      - name: Wait for JSON files to be written
        run: sleep 5  # Sleep for 5 seconds to ensure files are ready

      # Step 9: Generate Ansible inventory file
      - name: Generate Ansible inventory
        run: python3 generate_inventory.py

      - name: Check inventory.yml
        run: cat ansible/inventory.yml

      # Step 11: Generate nginx.conf
      - name: Generate nginx.conf
        run: python3 generate_nginx_conf.py

      - name: Check nginx.conf.j2
        run: cat ansible/roles/load_balancer/templates/nginx.conf.j2

      - name: Install jq
        run: sudo apt install -y jq

      # Step 12: Run Ansible playbook
      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.yml ansible/playbook.yml -e "backend_ips=$(terraform output -json backend_ips)"