name: Deploy Project

on:
  release:
    types: [published]

jobs:
  push_to_registries:
    name: Run Apache Load Balancer
    runs-on: ubuntu-20.04
    permissions:
        contents: read
        packages: write
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6  # Replace with your required version

      # Step 3: Install Ansible 
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible 

      # Step 4: Install jq
      - name: Install jq
        run: sudo apt install -y jq

      # Step 5: Write SSH Private Key
      - name: Write SSH Private Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > id_ecdsa
          chmod 600 id_ecdsa
          cat id_ecdsa

      # Step 6: Write SSH Public Key
      - name: Write SSH Public Key
        env:
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        run: |
          echo "$SSH_PUBLIC_KEY" > id_ecdsa.pub
          chmod 600 id_ecdsa.pub        

      # Step 7: Fix provider permissions 
      - name: Fix provider permissions
        run: chmod -R +x .terraform/providers

      # Step 8: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Step 9: Plan Terraform deployment
      - name: Plan Terraform
        run: terraform plan

      # Step 10: Apply Terraform configuration
      - name: Apply Terraform
        run: terraform apply -auto-approve

      # Step 11: Run Ansible playbook
      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory ansible/playbook.yml

      # Step 12: Set up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Step 13: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 14: Log in to the Container registry
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 15: Extract metadata for Docker    
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}
      
      # Step 16: Build and push Docker images        
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
