name: Deploy Project

on:
  release:
    types: [published]

jobs:
  push_to_registries:
    name: Push Docker image to the ghcr.io registry
    runs-on: ubuntu-20.04
    permissions:
        contents: read
        packages: write
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6  # Replace with your required version

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 4: Install Ansible and jq
      - name: Install Ansible and jq
        run: |
          sudo apt update
          sudo apt install -y ansible jq

      # Step 5: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Step 6: Plan Terraform deployment
      - name: Plan Terraform
        run: terraform plan

      # Step 7: Apply Terraform configuration
      - name: Apply Terraform
        run: terraform apply -auto-approve

      # Step 8: Generate inventory.json from Terraform output
      - name: Generate inventory.json
        run: terraform output -json > inventory.json

      # Step 9: Generate Ansible inventory file
      - name: Generate Ansible inventory
        run: python3 generate_inventory.py

      # Step 10: Generate backend_ips.json
      - name: Generate backend_ips.json
        run: terraform output -json backend_ips > backend_ips.json

      # Step 11: Generate nginx.conf
      - name: Generate nginx.conf
        run: python3 generate_nginx_conf.py

      # Step 12: Run Ansible playbook
      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.yml ansible/playbook.yml -e "backend_ips=$(terraform output -json backend_ips)"